### ISSUE TITLE
dataset PPI

### ISSUE THREAD

**Issue by StewLulu** [diningphil/CGMM#4]
I use the code in cmd `python Launch_Experiments.py --config-file config_CGMM.yml --inner-folds None --outer-folds 10 --dataset PPI`,and it shows as follow
Downloading https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip
Downloading https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip
Downloading https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip
Downloading https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip
Extracting DATA\PPI\raw\ppi.zip
Processing...
Extracting DATA\PPI\raw\ppi.zip
Processing...
Done!
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_2\\HOLDOUT_MS\\config_1\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_2\\HOLDOUT_MS\\config_2\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_2\\HOLDOUT_MS\\config_3\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_2\\HOLDOUT_MS\\config_4\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_2\\HOLDOUT_MS\\config_5\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_2\\HOLDOUT_MS\\config_6\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_2\\HOLDOUT_MS\\config_7\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_2\\HOLDOUT_MS\\config_8\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_2\\HOLDOUT_MS\\config_9\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_2\\HOLDOUT_MS\\config_10\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_2\\HOLDOUT_MS\\config_11\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_2\\HOLDOUT_MS\\config_12\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_3\\HOLDOUT_MS\\config_1\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_3\\HOLDOUT_MS\\config_2\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_3\\HOLDOUT_MS\\config_3\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_3\\HOLDOUT_MS\\config_4\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_3\\HOLDOUT_MS\\config_5\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_3\\HOLDOUT_MS\\config_6\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_3\\HOLDOUT_MS\\config_7\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_3\\HOLDOUT_MS\\config_8\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_3\\HOLDOUT_MS\\config_9\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_3\\HOLDOUT_MS\\config_10\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_3\\HOLDOUT_MS\\config_11\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_3\\HOLDOUT_MS\\config_12\\config_results.json'
Done!
Initializing layer 1 of CGMM...
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_4\\HOLDOUT_MS\\config_1\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_4\\HOLDOUT_MS\\config_2\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_4\\HOLDOUT_MS\\config_3\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_4\\HOLDOUT_MS\\config_4\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_4\\HOLDOUT_MS\\config_5\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_4\\HOLDOUT_MS\\config_6\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_4\\HOLDOUT_MS\\config_7\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_4\\HOLDOUT_MS\\config_8\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_4\\HOLDOUT_MS\\config_9\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_4\\HOLDOUT_MS\\config_10\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_4\\HOLDOUT_MS\\config_11\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_4\\HOLDOUT_MS\\config_12\\config_results.json'
likelihood at epoch 1 : -236272.47959490854
likelihood at epoch 2 : -189390.17753675583
likelihood at epoch 3 : -189390.17753779993
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_5\\HOLDOUT_MS\\config_1\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_5\\HOLDOUT_MS\\config_2\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_5\\HOLDOUT_MS\\config_3\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_5\\HOLDOUT_MS\\config_4\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_5\\HOLDOUT_MS\\config_5\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_5\\HOLDOUT_MS\\config_6\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_5\\HOLDOUT_MS\\config_7\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_5\\HOLDOUT_MS\\config_8\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_5\\HOLDOUT_MS\\config_9\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_5\\HOLDOUT_MS\\config_10\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_5\\HOLDOUT_MS\\config_11\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_5\\HOLDOUT_MS\\config_12\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_6\\HOLDOUT_MS\\config_1\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_6\\HOLDOUT_MS\\config_2\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_6\\HOLDOUT_MS\\config_3\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_6\\HOLDOUT_MS\\config_4\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_6\\HOLDOUT_MS\\config_5\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_6\\HOLDOUT_MS\\config_6\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_6\\HOLDOUT_MS\\config_7\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_6\\HOLDOUT_MS\\config_8\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_6\\HOLDOUT_MS\\config_9\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_6\\HOLDOUT_MS\\config_10\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_6\\HOLDOUT_MS\\config_11\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_6\\HOLDOUT_MS\\config_12\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_7\\HOLDOUT_MS\\config_1\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_7\\HOLDOUT_MS\\config_2\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_7\\HOLDOUT_MS\\config_3\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_7\\HOLDOUT_MS\\config_4\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_7\\HOLDOUT_MS\\config_5\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_7\\HOLDOUT_MS\\config_6\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_7\\HOLDOUT_MS\\config_7\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_7\\HOLDOUT_MS\\config_8\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_7\\HOLDOUT_MS\\config_9\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_7\\HOLDOUT_MS\\config_10\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_7\\HOLDOUT_MS\\config_11\\config_results.json'
[Errno 2] No such file or directory: 'RESULTS\\CGMM_PPI_assessment\\10_NESTED_CV\\OUTER_FOLD_7\\HOLDOUT_MS\\config_12\\config_results.json'

**Comment by diningphil** [comment]
It looks like the processes immediately stopped working. I suspect this may be caused by the configuration file not being set up properly. The last part of the README file may be of help.

Could you please paste here the configuration file you used?

Also, it would be a good idea to first run the command with the `--debug` argument, to see why a single process is suddenly terminating.

**Comment by diningphil** [comment]
Have you solved the issue? Otherwise I will close it for inactivity.

**Comment by StewLulu** [comment]
Yep




            
            
                
                    
                            
                                
                            
                            
                                570002752
                            
                    
                        
                            
                                    邮箱：570002752@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 12/28/2019 17:14, Federico Errica wrote: Have you solved the issue? Otherwise I will close it for inactivity.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/diningphil/CGMM/issues/4?email_source=notifications\u0026email_token=ANUIQ5JHE4L3XHXBCGGNWI3Q24KIJA5CNFSM4JRS5CIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHYF26A#issuecomment-569400696",
"url": "https://github.com/diningphil/CGMM/issues/4?email_source=notifications\u0026email_token=ANUIQ5JHE4L3XHXBCGGNWI3Q24KIJA5CNFSM4JRS5CIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHYF26A#issuecomment-569400696",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
